baseURL = "https://lipukule.org/"
languageCode = "tok"
title = "lipu kule"
theme = "lt"
paginate = 6
defaultContentLanguage = "tok"

[markup.goldmark.renderer]
    unsafe = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    lipu = "/lipu/:year/:month/:day/:slug/"
    mi = "/mi/:slug/"
    janpali = "/janpali/:slug"
    poki = "/poki/:slug"
    kule = "/kule/:slug"

[params]
    description = "lipu sona pi toki pona."

[taxonomies]
    poki = "poki"
    kule = "kule"
    janpali = "janpali"

[languages]
    [languages.tok]
    languageCode = 'tok'
    languageName = "toki pona pi sitelen Lasina"
    weight = 1
    enableMissingTranslationPlaceholders = true

    [languages.sp]
    languageCode = 'sp'
    languageName = "󱥬󱦖󱥔󱥍󱦗󱥠󱥔󱦘"
    weight = 2
    enableMissingTranslationPlaceholders = true

[security]
	[security.exec]
		allow = ['^go$', '^npx$', '^postcss$', '^babel$']


[build]
    writeStats = true
    [[build.cachebusters]]
        source = "(postcss|tailwind)\\.config\\.js"
        target = "css"
    [[build.cachebusters]]
        source = "assets/.*\\.(js|ts|jsx|tsx)"
        target = "js"
    [[build.cachebusters]]
        source = "assets/.*\\.(.*)$"
        target = "$1"
