baseURL = "https://lipukule.org/"
languageCode = "tok"
title = "lipu kule"
theme = "lt"
paginate = 6
DefaultContentLanguage = "tok"

[markup.goldmark.renderer]
    unsafe = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    lipu = "/lipu/:year/:month/:day/:slug/"
    mi = "/mi/:slug/"
    janpali = "/janpali/:slug"
    poki = "/poki/:slug"
    kule = "/kule/:slug"

[params]
    description = "lipu sona pi toki pona."

[taxonomies]
    poki = "poki"
    kule = "kule"
    janpali = "janpali"

[languages]
    [languages.tok]
    contentDir = "content/tok"
    languageName = "toki pona"
    weight = 1

[security]
	[security.exec]
		allow = ['^go$', '^npx$', '^postcss$', '^babel$']
